Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from policyengine_uk import IndividualSim


def get_cb_for_n_children(n):
    sim = IndividualSim(year=2022)
    for i in range(n):
        sim.add_person(age=10, name=str(i))
    sim.add_benunit(members=[str(i) for i in range(n)])
    return f'Â£{sim.calc("child_benefit").sum():.2f}'


pd.DataFrame(
    {
        "Number of children": list(range(1, 7)),
        "Child Benefit (Annual)": list(
            map(get_cb_for_n_children, range(1, 7))
        ),
    }
).set_index("Number of children")
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mImportError[0m                               Traceback (most recent call last)
[0;32m/tmp/ipykernel_2289/935488397.py[0m in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0;31m [0;32mfrom[0m [0mpolicyengine_uk[0m [0;32mimport[0m [0mIndividualSim[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0;34m[0m[0m
[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;32mdef[0m [0mget_cb_for_n_children[0m[0;34m([0m[0mn[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m     [0msim[0m [0;34m=[0m [0mIndividualSim[0m[0;34m([0m[0myear[0m[0;34m=[0m[0;36m2022[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;31mImportError[0m: cannot import name 'IndividualSim' from 'policyengine_uk' (/home/runner/work/policyengine-uk/policyengine-uk/policyengine_uk/__init__.py)

